# Generated by Django 5.1.1 on 2024-09-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='description',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
